title: BBA Keras-CVAE DBSCAN Production Run
resource: llnl.lassen
queue: exempt
schema_: local
project: $PROJECTID
walltime_min: 720
max_iteration: 120
cpus_per_node: 40
gpus_per_node: 4
hardware_threads_per_cpu: 4
experiment_directory: /p/gpfs1/$USER/runs/ddmd_production_runs/bba-12hr-keras-dbscan-run-1
node_local_path: /tmp
molecular_dynamics_stage:
    pre_exec:
    - . /etc/profile.d/conda.sh
    - module load cuda/9.1.85
    - unset PYTHONPATH
    - conda activate /p/gpfs1/$USER/envs/conda-openmm
    executable: /p/gpfs1/$USER/envs/conda-openmm/bin/python
    arguments:
    - /p/gpfs1/$USER/src/DeepDriveMD-pipeline/deepdrivemd/sim/openmm/run_openmm.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    num_tasks: 120
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        pdb_file: set_by_deepdrivemd
        initial_pdb_dir: /p/gpfs1/$USER/data/bba/ddmd_input
        solvent_type: implicit
        top_suffix: null
        simulation_length_ns: 10.0
        report_interval_ps: 50.0
        dt_ps: 0.002
        temperature_kelvin: 310.0
        heat_bath_friction_coef: 1.0
        wrap: false
        reference_pdb_file: /p/gpfs1/$USER/data/bba/ddmd_input/1FME-folded.pdb
        openmm_selection:
        - CA
        mda_selection: protein and name CA
        threshold: 8.0
        contact_map: true
        point_cloud: false
        fraction_of_contacts: false
        in_memory: false
aggregation_stage:
    pre_exec: []
    executable: ''
    arguments: []
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    skip_aggregation: true
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
machine_learning_stage:
    pre_exec:
    - . /etc/profile.d/conda.sh
    - module load gcc/7.3.1
    - module load cuda/10.1.243
    - export LANG=en_US.utf-8
    - export LC_ALL=en_US.utf-8
    - export HDF5_USE_FILE_LOCKING=FALSE
    - export IBM_POWERAI_LICENSE_ACCEPT=yes
    - unset PYTHONPATH
    - conda activate /p/gpfs1/$USER/envs/conda-keras-powerai
    - unset CUDA_VISIBLE_DEVICES
    - export OMP_NUM_THREADS=4
    executable: /p/gpfs1/$USER/envs/conda-keras-powerai/bin/python
    arguments:
    - /p/gpfs1/$USER/src/DeepDriveMD-pipeline/deepdrivemd/models/keras_cvae/train.py
    cpu_reqs:
        processes: 1
        process_type: MPI
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    retrain_freq: 2
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        model_tag: set_by_deepdrivemd
        init_weights_path: null
        last_n_h5_files: 120
        k_random_old_h5_files: 120
        dataset_name: contact_map
        initial_shape:
        - 28
        - 28
        final_shape:
        - 28
        - 28
        - 1
        initial_epochs: 15
        epochs: 20
        batch_size: 32
        split_pct: 0.8
        shuffle: true
        latent_dim: 10
        conv_layers: 4
        conv_filters:
        - 64
        - 64
        - 64
        - 64
        conv_filter_shapes:
        -   - 3
            - 3
        -   - 3
            - 3
        -   - 3
            - 3
        -   - 3
            - 3
        conv_strides:
        -   - 1
            - 1
        -   - 2
            - 2
        -   - 1
            - 1
        -   - 1
            - 1
        encoder_kernel_sizes:
        - 5
        - 5
        - 3
        - 1
        - 1
        dense_layers: 1
        dense_neurons:
        - 128
        dense_dropouts:
        - 0.25
model_selection_stage:
    pre_exec:
    - . /etc/profile.d/conda.sh
    - export IBM_POWERAI_LICENSE_ACCEPT=yes
    - unset PYTHONPATH
    - conda activate /p/gpfs1/$USER/envs/conda-keras-powerai
    executable: /p/gpfs1/$USER/envs/conda-keras-powerai/bin/python
    arguments:
    - /p/gpfs1/$USER/src/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        retrain_freq: 2
        checkpoint_dir: checkpoint
        checkpoint_suffix: .h5
agent_stage:
    pre_exec:
    - . /etc/profile.d/conda.sh
    - export IBM_POWERAI_LICENSE_ACCEPT=yes
    - unset PYTHONPATH
    - conda activate /p/gpfs1/$USER/envs/conda-keras-powerai
    - export LANG=en_US.utf-8
    - export LC_ALL=en_US.utf-8
    - unset CUDA_VISIBLE_DEVICES
    - export OMP_NUM_THREADS=4
    executable: /p/gpfs1/$USER/envs/conda-keras-powerai/bin/python
    arguments:
    - /p/gpfs1/$USER/src/DeepDriveMD-pipeline/deepdrivemd/agents/lof/lof.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 12
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        num_intrinsic_outliers: 500
        num_extrinsic_outliers: 120
        intrinsic_score: dbscan
        extrinsic_score: rmsd
        n_traj_frames: 200
        n_most_recent_h5_files: 120
        k_random_old_h5_files: 120
        sklearn_num_jobs: -1
        model_type: "keras_cvae"
        inference_batch_size: 1024
